%% Create Deep Learning Network Architecture 
% Script for creating the layers for a deep learning network with the following 
% properties:
%%
% 
%  Number of layers: 8
%  Number of connections: 7
%
%% 
% Run the script to create the layers in the workspace variable |net|.
% 
% To learn more, see <matlab:helpview('deeplearning','generate_matlab_code') 
% Generate MATLAB Code From Deep Network Designer>.
% 
% Auto-generated by MATLAB on 26-May-2026 14:56:15
%% Create Datastorage to import Trainingdata
%% Creating Trainingdata Folder with labels


% Die oberen Kommentare sind durch den Matlab Designer entstanden.
clear;
clc;
lbs = "";
lbs_2 = "";
sigds_D = signalDatastore(lbs, "IncludeSubfolders",true,"ReadFcn",@readmatrix);
sigds_R = signalDatastore(lbs_2, "IncludeSubfolders",true,"ReadFcn",@readmatrix);
fname_rate = sigds_R.Files;
fname_Depth = sigds_D.Files;
labels = folders2labels(sigds_D);
labels_2 = folders2labels(sigds_R);
%% Importing Trainingdata for Depth Training

Fs = 100; % Damit die Daten künstlich auf 100 Hz gestreckt werden, dafür wird interpolation gebraucht, welches gewisse Fehler in den Datensatz einbaut.
XTrain_Gesamt_Depth = {};
Tiefe_Gesamt = categorical();


for k = 1:length(fname_Depth)
    
    data = readmatrix(fname_Depth{k},"Delimiter", ";","DecimalSeparator", ",");
    acc = data(:,4);
    t = data(:,5);
    acc = acc - mean(acc);
    t_inter = t(1) : (1/Fs): t(end);
    acc_Resample_Depth = interp1(t, acc, t_inter,"linear");
    aktuelle_Tiefe = labels(k);
    fenster_Depth = 2 * Fs;
    Schrittweite_Depth = 0.5*Fs; % Wichtig für die Anwendung Sliding Window ausgewählte Schrittweite 
    
    Anzahlwerte_Depth = length(acc_Resample_Depth);

    Anzahlfenster_Depth = round((Anzahlwerte_Depth - fenster_Depth) / Schrittweite_Depth); % Anzahl der maximalen Fenster bestimmen
    


    XTrain_Block_Depth = cell(Anzahlfenster_Depth, 1);
    
    Tiefe_Block  = repmat(aktuelle_Tiefe, Anzahlfenster_Depth, 1);
    
    for i = 1:Anzahlfenster_Depth
        startIndex_depth = (i - 1) * Schrittweite_Depth + 1;
        endIndex_depth   = startIndex_depth + fenster_Depth - 1;
        
        % Fenster ausschneiden und als Zeilenvektor (1x200) speichern
        XTrain_Block_Depth{i} = reshape(acc_Resample_Depth(startIndex_depth:endIndex_depth), 1, []);         
    end
    
    XTrain_Gesamt_Depth = [XTrain_Gesamt_Depth; XTrain_Block_Depth];
    Tiefe_Gesamt  = [Tiefe_Gesamt; Tiefe_Block]; 
    %Nachder Iteration befinden sich die Trainingsfenster in XTrain und
    %Tiefe_gesamt besitzt die zugewiesenen Label
end


%% Importing Trainingsdata for Rate Training

Fs = 100;
XTrain_Gesamt_rate = {};
rate_Gesamt = categorical();

for k = 1:length(fname_rate)
    
    data = readmatrix(fname_rate{k},"Delimiter", ";","DecimalSeparator", ",");
    acc = data(:,4);
    t = data(:,5);
    acc = acc - mean(acc);
    t_inter = t(1) : (1/Fs): t(end);
    acc_Resample_rate = interp1(t, acc, t_inter,"linear");
    aktuelle_rate = labels_2(k);
    fenster_rate = 2 * Fs;
    Schrittweite_rate = 0.5 * Fs; % Wichtig für die Anwendung Sliding Window heißt ich geh durch 
    
    Anzahlwerte_rate = length(acc_Resample_rate);

    Anzahlfenster_rate = round((Anzahlwerte_rate - fenster_rate) / Schrittweite_rate);

    XTrain_Block_rate = cell(Anzahlfenster_rate, 1);

    rate_Block  = repmat(aktuelle_rate, Anzahlfenster_rate, 1);
    
    for i = 1:Anzahlfenster_rate
        startIndex_rate = (i - 1) * Schrittweite_rate + 1;
        endIndex_rate   = startIndex_rate + fenster_rate - 1;
        
        % Fenster ausschneiden und als Zeilenvektor (1x200) speichern
        XTrain_Block_rate{i} = reshape(acc_Resample_rate(startIndex_rate:endIndex_rate), 1, []);
        
             
    end
    
    XTrain_Gesamt_rate = [XTrain_Gesamt_rate; XTrain_Block_rate];
    rate_Gesamt  = [rate_Gesamt; rate_Block];   
end
%% 
% 
%% Creating Network for Deep Learning
%% Add Layer Branches 
% Each branch is a linear array of layers.

Layer_Tiefe = [
    sequenceInputLayer(1,"Name","input")
    convolution1dLayer(5,16,"Name","conv1d","Padding","same")
    reluLayer("Name","relu")
    lstmLayer(64,"Name","lstm","OutputMode","last")
    dropoutLayer(0.5,"Name","dropout")
    fullyConnectedLayer(4,"Name","fc_tiefe")
    softmaxLayer("Name","softmax")
    classificationLayer("Name","Output")];

Layer_Rate = [
    sequenceInputLayer(1,"Name","input")
    convolution1dLayer(5,16,"Name","conv1d","Padding","same")
    reluLayer("Name","relu")
    lstmLayer(64,"Name","lstm","OutputMode","last")
    dropoutLayer(0.5,"Name","dropout")
    fullyConnectedLayer(4,"Name","fc_rate")
    softmaxLayer("Name","softmax")
    classificationLayer("Name","Output")];

options = trainingOptions("adam", ...
    'MaxEpochs', 50, ...
    'MiniBatchSize', 32, ...
    'Shuffle', 'every-epoch', ...
    'Plots', 'training-progress', ...
    'Verbose', false);
% Gewählte trainingsparameter


disp('Starte Training für die Tiefe...');
trainedNet_Tiefe = trainNetwork(XTrain_Gesamt_Depth, Tiefe_Gesamt, Layer_Tiefe, options);

disp('Starte Training für die Rate...');
trainedNet_Rate = trainNetwork(XTrain_Gesamt_rate, rate_Gesamt, Layer_Rate, options);

disp('Beide KIs erfolgreich trainiert!');


save('Meine_CPR_Modelle_2.mat', 'trainedNet_Tiefe', 'trainedNet_Rate');
%% Exportieren des Modells in ONNX
exportONNXNetwork(trainedNet_Rate, "frequency_model.onnx");
exportONNXNetwork(trainedNet_Tiefe, "depth_model.onnx");